const getDefaultClientPermissions = clientType => {
  const MAP = {
    app: {
      userOfCmsRead: false,
      projectCreate: false,
      projectRead: false,
      projectUpdate: false,
      projectDelete: false,
      apiTokenCreate: false,
      apiTokenRead: false,
      apiTokenUpdate: false,
      apiTokenDelete: false,
      apiTokenPermissionsRead: false,
      apiTokenPermissionsUpdate: false,
      userOfProjectCreate: false,
      userOfProjectRead: false,
      userOfProjectDelete: false,
      userPermissionsRead: false,
      userPermissionsUpdate: false,
      fileCreate: true,
      fileRead: true,
      modelCreate: true,
      modelRead: true,
      modelUpdate: true,
      modelDelete: true,
      entryCreate: true,
      entryRead: true,
      entryUpdate: true,
      entryDelete: true,
    },
    user: {
      userOfCmsRead: true,
      projectCreate: true,
      projectRead: true,
      projectUpdate: true,
      projectDelete: true,
      apiTokenCreate: true,
      apiTokenRead: true,
      apiTokenUpdate: true,
      apiTokenDelete: true,
      apiTokenPermissionsRead: true,
      apiTokenPermissionsUpdate: true,
      userOfProjectCreate: true,
      userOfProjectRead: true,
      userOfProjectDelete: true,
      userPermissionsRead: true,
      userPermissionsUpdate: true,
      fileCreate: true,
      fileRead: true,
      modelCreate: true,
      modelRead: true,
      modelUpdate: true,
      modelDelete: true,
      entryCreate: true,
      entryRead: true,
      entryUpdate: true,
      entryDelete: true,
    },
  }
  return MAP[clientType]
}

module.exports = { getDefaultClientPermissions }
